 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javacrud.tech;

import java.util.Properties;

import java.util.Date;
import javacrud.control.ConfigDAO;
import javacrud.model.Configuration;
import javax.mail.Session;

import javax.mail.PasswordAuthentication;
import javax.mail.Message;

import javax.mail.MessagingException;
import javax.mail.Transport;

import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;

import javax.activation.DataHandler;

/**
 *
 * @author g.gerbaud
 */
public class GestionSMTP extends javax.swing.JFrame {

    //Propriétées
    String user;
    String password;
    String bdd;
    String hote;
    String port;
    Session session;
    MimeMessage message; //On verra après
    private String mailMsg;

    /**
     * Creates new form GestionSMTP
     */
    public GestionSMTP() {
        Configuration configBDD = ConfigDAO.getConfiguration();
        this.user = "gerbaudguilhem@gmail.com";
        this.password = "HIlLm_8TVZ.^2+xEEBBD*~awGXf^";
        this.bdd = configBDD.getMysqlDb();
                
        initCon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initCon() {
// Paramétrer l'objet "session" 
        Properties props = new Properties();
        props.put("mail.transport.protocol", "smtp");
        props.put("mail.smtp.host", "mail.st2msi.net"); // hébergeur smtp
        props.put("mail.stmp.port", "465"); // port smtp
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.socketFactory.port", "465"); //SSL Port
        props.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory"); //SSL Factory Class
        this.session = Session.getDefaultInstance(props, new javax.mail.Authenticator() {

            protected PasswordAuthentication getPasswordAuthentication() {

                return new PasswordAuthentication(user, password);

            }
        });
    }

    public void sendMsg() throws Exception { // exception traité par l'appelant

        this.message = new MimeMessage(session);

        this.message.setFrom(new InternetAddress(user));

        this.message.addRecipient(Message.RecipientType.TO, new InternetAddress(mailTo.strip()));

        this.message.addHeader("Content-type", "text/HTML; charset=UTF-8");

        this.message.addHeader("format", "flowed");

        this.message.addHeader("Content-Transfer-Encoding", "8bit");

        this.message.setHeader("X-Mailer", "st2msi.net/JavaMail version 1.6.2");

        this.message.setSentDate(new Date());

        this.message.setSubject(mailObj.strip(), "UTF-8");

        message.setText(mailMsg, "UTF-8");

        //send the message 
        session.setDebug(true); // passer à false en production

        Transport.send(message);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionSMTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionSMTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionSMTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionSMTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionSMTP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    public void setMailObj(String strip) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void setMailTo(String strip) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void setMailMsg(String text) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void closeSMTPCon() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private static class mailObj {

        private static String strip() {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public mailObj() {
        }
    }

    private static class mailTo {

        private static String strip() {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public mailTo() {
        }
    }

   
}
