/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javacrud.view;
import javacrud.control.UtilisateurDAOImp;
import javacrud.model.Utilisateur;
import javax.swing.JOptionPane;

/**
 *
 * @author Guilhem
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldPseudo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldMDP = new javax.swing.JTextField();
        jButtonQuitter = new javax.swing.JButton();
        jButtonConnexion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Pseudo");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 50, 70, 20);
        getContentPane().add(jTextFieldPseudo);
        jTextFieldPseudo.setBounds(110, 70, 230, 22);

        jLabel2.setText("Mot de passe");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 110, 90, 20);
        getContentPane().add(jTextFieldMDP);
        jTextFieldMDP.setBounds(110, 130, 230, 22);

        jButtonQuitter.setText("Quitter");
        getContentPane().add(jButtonQuitter);
        jButtonQuitter.setBounds(50, 210, 72, 22);

        jButtonConnexion.setText("Connexion");
        jButtonConnexion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonConnexionMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonConnexion);
        jButtonConnexion.setBounds(310, 210, 90, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConnexionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonConnexionMouseClicked
        if(new UtilisateurDAOImp().connexion(jTextFieldPseudo.getText(), jTextFieldMDP.getText())){
            JOptionPane.showMessageDialog(null, "Connexion réussie");
        }else{
            JOptionPane.showMessageDialog(null, "échec de connexion");
        }
    }//GEN-LAST:event_jButtonConnexionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConnexion;
    private javax.swing.JButton jButtonQuitter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextFieldMDP;
    private javax.swing.JTextField jTextFieldPseudo;
    // End of variables declaration//GEN-END:variables
}
