/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package javacrud.view;

import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javacrud.model.Configuration;
import javacrud.control.ConfigDAO;
import javacrud.tech.XMLLocal;

/**
 *
 * @author g.gerbaud
 */
public class Parametre extends javax.swing.JDialog {

    private void paramConfigDansChampsSaisie() {
        Configuration cDAO = ConfigDAO.getConfiguration();
        uiMailProtocol.setText(cDAO.getMailProtocol());
        uiMailHost.setText(cDAO.getMailHost());
        uiMailPort.setText(cDAO.getMailPort());
        uiMailUser.setText(cDAO.getMailUser());
        uiMailMP.setText(cDAO.getMailPass());

        uiMysqlDB.setText(cDAO.getMysqlDb());
        uiMysqlHost.setText(cDAO.getMysqlHost());
        uiMysqlPort.setText(cDAO.getMysqlPort());
        uiMysqlUser.setText(cDAO.getMysqlUser());
        uiMysqlMP.setText(cDAO.getMysqlPass());
    }

    /**
     * Creates new form NewJDialog
     */
    public Parametre(java.awt.Frame parent, boolean modal) throws Exception {
        super(parent, modal);
        initComponents();
        XMLLocal.getDocument();
        paramConfigDansChampsSaisie();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        valider = new javax.swing.JButton();
        enTete = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        mailPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        uiMailProtocol = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        uiMailHost = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        uiMailPort = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        uiMailUser = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        uiMailMP = new javax.swing.JTextField();
        bddPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        uiMysqlDB = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        uiMysqlHost = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        uiMysqlPort = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        uiMysqlUser = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        uiMysqlMP = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(681, 450));
        setMinimumSize(new java.awt.Dimension(681, 450));
        setPreferredSize(new java.awt.Dimension(681, 450));
        setResizable(false);
        setSize(new java.awt.Dimension(681, 450));
        getContentPane().setLayout(null);

        valider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/valid_20.png"))); // NOI18N
        valider.setText("Valider");
        valider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                validerMouseClicked(evt);
            }
        });
        valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerActionPerformed(evt);
            }
        });
        getContentPane().add(valider);
        valider.setBounds(30, 370, 110, 26);

        enTete.setBackground(new java.awt.Color(153, 153, 153));
        enTete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enTete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/java_64.png"))); // NOI18N
        enTete.setText("PARAMETRES DE L'APPLICATION");
        enTete.setOpaque(true);
        getContentPane().add(enTete);
        enTete.setBounds(0, 0, 680, 70);

        jLabel9.setText("Protocole :");

        uiMailProtocol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uiMailProtocolActionPerformed(evt);
            }
        });

        jLabel10.setText("Hôte :");

        jLabel8.setText("Utilisateur :");

        jLabel11.setText("Port :");

        jLabel12.setText("Mot de pass :");

        javax.swing.GroupLayout mailPanelLayout = new javax.swing.GroupLayout(mailPanel);
        mailPanel.setLayout(mailPanelLayout);
        mailPanelLayout.setHorizontalGroup(
            mailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mailPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(mailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(mailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(uiMailUser)
                    .addComponent(uiMailMP)
                    .addComponent(uiMailPort)
                    .addComponent(uiMailHost)
                    .addComponent(uiMailProtocol, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(225, Short.MAX_VALUE))
        );
        mailPanelLayout.setVerticalGroup(
            mailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mailPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(mailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(uiMailProtocol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(uiMailHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(uiMailPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(uiMailUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(uiMailMP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Serveur de messagerie", mailPanel);

        jLabel3.setText("Utilisateur :");

        uiMysqlDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uiMysqlDBActionPerformed(evt);
            }
        });

        jLabel4.setText("Base de données :");

        jLabel5.setText("Hôte :");

        jLabel6.setText("Port :");

        jLabel7.setText("Mot de pass :");

        javax.swing.GroupLayout bddPanelLayout = new javax.swing.GroupLayout(bddPanel);
        bddPanel.setLayout(bddPanelLayout);
        bddPanelLayout.setHorizontalGroup(
            bddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bddPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(bddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(bddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(uiMysqlUser)
                    .addComponent(uiMysqlMP)
                    .addComponent(uiMysqlPort)
                    .addComponent(uiMysqlHost)
                    .addComponent(uiMysqlDB, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(201, Short.MAX_VALUE))
        );
        bddPanelLayout.setVerticalGroup(
            bddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bddPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(bddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(uiMysqlDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(uiMysqlHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(uiMysqlPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(uiMysqlUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(uiMysqlMP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Base de données", bddPanel);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(20, 90, 640, 270);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/back_ec.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 680, 420);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 680, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uiMysqlDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uiMysqlDBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uiMysqlDBActionPerformed

    private void uiMailProtocolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uiMailProtocolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uiMailProtocolActionPerformed

    private void validerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_validerMouseClicked
        Configuration c = ConfigDAO.getConfiguration();
        c.setMailHost(uiMailHost.getText());
        c.setMailPass(uiMailMP.getText());;
        c.setMailPort(uiMailPort.getText());
        c.setMailProtocol(uiMailProtocol.getText());
        c.setMailUser(uiMailUser.getText());
        c.setMysqlDb(uiMysqlDB.getText());
        c.setMysqlHost(uiMysqlHost.getText());
        c.setMysqlPass(uiMysqlMP.getText());
        c.setMysqlPort(uiMysqlPort.getText());
        c.setMysqlUser(uiMysqlUser.getText());

        ConfigDAO.saveXMLFile(c);
    }//GEN-LAST:event_validerMouseClicked

    private void validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_validerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Parametre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Parametre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Parametre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Parametre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    Parametre dialog = new Parametre(new javax.swing.JFrame(), true);
                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                        @Override
                        public void windowClosing(java.awt.event.WindowEvent e) {
                            System.exit(0);
                        }
                    });
                    dialog.setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(Parametre.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bddPanel;
    private javax.swing.JLabel enTete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel mailPanel;
    private javax.swing.JTextField uiMailHost;
    private javax.swing.JTextField uiMailMP;
    private javax.swing.JTextField uiMailPort;
    private javax.swing.JTextField uiMailProtocol;
    private javax.swing.JTextField uiMailUser;
    private javax.swing.JTextField uiMysqlDB;
    private javax.swing.JTextField uiMysqlHost;
    private javax.swing.JTextField uiMysqlMP;
    private javax.swing.JTextField uiMysqlPort;
    private javax.swing.JTextField uiMysqlUser;
    private javax.swing.JButton valider;
    // End of variables declaration//GEN-END:variables

}
